---
  name: CICD

  on:
    workflow_dispatch:

  jobs: 
    depoly:
      runs-on: ubuntu-latest

      steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username:  ${{ secrets.USER }}
            key:  ${{ secrets.KEY }}
            port:  ${{ secrets.PORT }}
            script: |
                cd ~/framesify
                git pull
                source venv/bin/activate
                pip install -r requirements.txt
                deactivate
                sudo systemctl restart framesify